# https://taskfile.dev

version: '2'
#silent: true

expansions: 5

vars:
  EXE_FILE: "{{.EXE_DIR}}/{{.EXE_NAME}}"

tasks:
  clean:
    cmds:
      - cmd: "{{.RM_RF}} {{.BUILD_DIR}}"
        ignore_error: true
      - cmd: "{{.RM}} src/parser/*.gen.go"
        ignore_error: true
      - cmd: "{{.RM}} 'src/parser/*.gen.go'"
        ignore error: true

  download-antlr:
    status:
      - "test -f {{.ANTLR_JAR}}"
    cmds:
      - cmd: "{{.MKDIR}} \"{{.ANTLR_DIR}}\""
      - cmd: "curl -o {{.ANTLR_JAR}} https://www.antlr.org/download/antlr-{{.ANTLR_VERSION}}-complete.jar"

  build-parser:
    deps: [download-antlr]
    sources:
      - src/parser/QuarkLexer.g4
      - src/parser/QuarkParser.g4
    generates:
      - src/parser/quark_lexer.gen.go
      - src/parser/quark_parser.gen.go
      - src/parser/quarkparser_base_visitor.gen.go
      - src/parser/quarkparser_visitor.gen.go
      - src/parser/quarkparser_base_listener.go
      - src/parser/quarkparser_listen.go
    cmds:
      - "{{.ANTLR}} -Xexact-output-dir -Dlanguage=Go -o ./src/parser src/parser/QuarkLexer.g4"
      - "{{.ANTLR}} -Xexact-output-dir -lib ./src/parser -o ./src/parser -visitor -listener -Dlanguage=Go src/parser/QuarkParser.g4"

  build:
    deps: [build-parser]
    sources:
      - src/**/*.go
    generates:
      - "{{.EXE_FILE}}"
    method: checksum
    cmds:
      - cmd: echo "building executable at {{.EXE_FILE}}"
      - cmd: go build -o "{{.EXE_FILE}}" src/pkg/quarkc/main.go
      - cmd: echo "done!"

  run:
    deps: [build]
    cmds:
      - "{{.EXE_FILE}} {{.INFILE}}"

  test:
    deps: [build]
    cmds:
      - go test ./...
